const generateMonthDays = (month: number, theme: string): DailyTask[] => {
  return Array.from({ length: 30 }, (_, i) => ({
    day: i + 1,
    title: `Sequence ${month}.${(i + 1).toString().padStart(2, '0')}: ${theme}`,
    objective: `Mastering advanced ${theme.toLowerCase()} primitives.`,
    conceptualWhy: `Elite architecture requires mastery of the unit. Sequence ${i + 1} bridges the gap between theory and production.`,
    funnyStory: `The developer who thought they could out-smart the ${theme} layer... their terminal is still screaming today.`,
    storyImageUrl: `https://images.unsplash.com/photo-${[
      '1451187580459-43490279c0fa',
      '1550751827-4bd374c3f58b',
      '1518770660439-4636190af475',
      '1517077304055-6e89abbf09b0',
      '1504384308090-c894fdcc538d'
    ][Math.floor(Math.random() * 5)]}?auto=format&fit=crop&q=80&w=800`,
    practicalUsage: `Building high-performance ${theme.toLowerCase()} systems at scale.`,
    detailedTheory: [{
      title: `${theme} Nexus Point ${i + 1}`,
      description: `Optimizing the ${theme.toLowerCase()} synchronization matrix for sub-millisecond latency.`,
      imageUrl: "https://images.unsplash.com/photo-1518433278988-78ef99ea0524?auto=format&fit=crop&q=80&w=800"
    }],
    resources: [
      { type: 'video', label: `Mastering ${theme} Layer`, url: 'https://www.youtube.com/', difficulty: 'Intermediate', duration: '12:45', provider: 'Odyssey Intelligence' }
    ],
    quiz: {
      question: `What is the primary constraint of the ${theme} interface in this sequence?`,
      options: ["Latency sync", "Logical state", "Physical heat", "Data density"],
      correctIndex: 0,
      explanation: "Latency synchronization is the ultimate goal of high-fidelity architectural units."
    }
  }));
};

export const INITIAL_ROADMAP: RoadmapModule[] = [
  {
    id: 'm0',
    month: 0,
    title: 'Silicon Foundations',
    description: 'Deconstruct the physical reality of computing.',
    conceptualWhy: 'Hardware is the stage; software is the play.',
    funnyStory: 'The Post-it Note Database.',
    practicalUsage: 'System performance.',
    topics: ['Transistors', 'Logic Gates', 'Binary'],
    skills: ['Architecture', 'Logic'],
    status: ModuleStatus.COMPLETED,
    previewImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonth0Days(),
    masteryProject: { title: 'Logic Lab', description: 'Build an 8-bit adder.' },
    resources: [],
    progress: 100
  },
  {
    id: 'm1',
    month: 1,
    title: 'The Kernel Authority',
    description: 'Master the operating systems and kernel interfaces.',
    conceptualWhy: 'The OS is the traffic controller.',
    funnyStory: 'The Waiter and the Burger.',
    practicalUsage: 'High-concurrency systems.',
    topics: ['Kernels', 'Syscalls', 'Memory Management'],
    skills: ['OS', 'Performance'],
    status: ModuleStatus.CURRENT,
    previewImage: 'https://images.unsplash.com/photo-1518433278988-78ef99ea0524?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonth1Days(),
    masteryProject: { title: 'Kernel Bridge', description: 'Implement a basic shell.' },
    resources: [],
    progress: 3
  },
  {
    id: 'm2',
    month: 2,
    title: 'The Network Nexus',
    description: 'Navigate the invisible highways of the internet.',
    conceptualWhy: 'Understanding the layers of data travel.',
    funnyStory: 'Bob the Packet.',
    practicalUsage: 'API design.',
    topics: ['TCP/IP', 'HTTP/3', 'WebSockets'],
    skills: ['Networking', 'Protocols'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1558494949-ef0109556754?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(2, "Network Protocol"),
    masteryProject: { title: 'Protocol Pioneer', description: 'Build a TCP chat application.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm3',
    month: 3,
    title: 'The Data Forge',
    description: 'Master persistent storage and data modeling.',
    conceptualWhy: 'Refining information into intelligence.',
    funnyStory: 'Sally and the 4 million rows.',
    practicalUsage: 'Scalable data systems.',
    topics: ['SQL', 'NoSQL', 'Indexing'],
    skills: ['Database', 'Optimization'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(3, "Data Management"),
    masteryProject: { title: 'Data Architect', description: 'Design an e-commerce schema.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm4',
    month: 4,
    title: 'The Frontend Frontier',
    description: 'Craft pixel-perfect interfaces.',
    conceptualWhy: 'The UI is the face of your application.',
    funnyStory: 'Centering a div for 3 hours.',
    practicalUsage: 'Responsive web engineering.',
    topics: ['HTML5', 'CSS Grid', 'Animation'],
    skills: ['Frontend', 'UI/UX'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(4, "UI Engineering"),
    masteryProject: { title: 'Pixel Perfect', description: 'Clone a professional landing page.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm5',
    month: 5,
    title: 'The JavaScript Engine',
    description: 'Master the language that powers the web.',
    conceptualWhy: 'The lingua franca of the internet.',
    funnyStory: 'Why 0.1 + 0.2 isn\'t 0.3.',
    practicalUsage: 'Interactive applications.',
    topics: ['ES6+', 'Async/Await', 'Closures'],
    skills: ['JavaScript', 'Logic'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(5, "JS Engine"),
    masteryProject: { title: 'JS Mastery', description: 'Build a custom Promise.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm6',
    month: 6,
    title: 'The React Revolution',
    description: 'Build declarative component systems.',
    conceptualWhy: 'Components are the LEGO blocks of UI.',
    funnyStory: 'The re-render that broke the world.',
    practicalUsage: 'Modern SPA development.',
    topics: ['Hooks', 'State', 'Context'],
    skills: ['React', 'Architecture'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(6, "React Framework"),
    masteryProject: { title: 'React Architect', description: 'Build a Kanban board.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm7',
    month: 7,
    title: 'The Node Nexus',
    description: 'Extend JavaScript to the server.',
    conceptualWhy: 'Enabling fullstack JavaScript development.',
    funnyStory: 'The infinite event loop.',
    practicalUsage: 'REST APIs & Microservices.',
    topics: ['Express', 'Middleware', 'Auth'],
    skills: ['Node.js', 'Backend'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(7, "Backend Logic"),
    masteryProject: { title: 'API Architect', description: 'Build an Auth system.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm8',
    month: 8,
    title: 'TypeScript Transformation',
    description: 'Add static typing for enterprise quality.',
    conceptualWhy: 'Catching bugs before they reach production.',
    funnyStory: 'The "any" that hid a disaster.',
    practicalUsage: 'Scalable software engineering.',
    topics: ['Types', 'Interfaces', 'Generics'],
    skills: ['TypeScript', 'Safety'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(8, "Type Systems"),
    masteryProject: { title: 'Type Master', description: 'Migrate a JS app to TS.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm9',
    month: 9,
    title: 'The Testing Temple',
    description: 'Master automated quality assurance.',
    conceptualWhy: 'Untested code is just broken code waiting.',
    funnyStory: 'It works on my machine...',
    practicalUsage: 'Reliable deployment.',
    topics: ['Unit', 'E2E', 'TDD'],
    skills: ['QA', 'Reliability'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1576444356170-66073046b1bc?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(9, "Software Testing"),
    masteryProject: { title: 'Test Champion', description: 'Achieve 95% coverage.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm10',
    month: 10,
    title: 'The DevOps Domain',
    description: 'Automate deployment pipelines.',
    conceptualWhy: 'Shipping fast and reliably with CI/CD.',
    funnyStory: 'Friday 5 PM Code Deploy.',
    practicalUsage: 'Continuous integration.',
    topics: ['Docker', 'AWS', 'Actions'],
    skills: ['Cloud', 'DevOps'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(10, "DevOps Mastery"),
    masteryProject: { title: 'DevOps Engineer', description: 'Build a full pipeline.' },
    resources: [],
    progress: 0
  },
  {
    id: 'm11',
    month: 11,
    title: 'The Scale Summit',
    description: 'Design systems for global mastery.',
    conceptualWhy: 'Handling millions of concurrent signals.',
    funnyStory: 'The database that went to space.',
    practicalUsage: 'Elite platform engineering.',
    topics: ['Caching', 'Microservices', 'Load Sync'],
    skills: ['Architecture', 'Scale'],
    status: ModuleStatus.LOCKED,
    previewImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200',
    dailySchedule: generateMonthDays(11, "Global Systems"),
    masteryProject: { title: 'Scale Architect', description: 'Deploy global infrastructure.' },
    resources: [],
    progress: 0
  }
];
